# Use root/example as user/password credentials
version: '3.1'

services:

  # db:
  #   image: mysql
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: coferment
  #     MYSQL_DATABASE: cup_management
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - beanedout:/var/lib/mysql_cup
  # cupping_manager:
  #   image: cupping_manager:latest
  #   container_name: cupping_manager
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./connectors/credentials.json:/usr/src/app/connectors/credentials.json
  #     - ./connectors/token.json:/usr/src/app/connectors/token.json
  #   environment:
  #     - APP_ENV=development
  #   command: ["execute_cron"]
  # version: '3.8'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Expose Prometheus UI

# volumes:
#   beanedout:
